# Generated by Django 4.2.7 on 2026-02-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('assessments', '0003_assessmentquestion_complexity'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassessmentattempt',
            name='test_domains',
            field=models.ManyToManyField(blank=True, help_text="Domains this test was taken for (e.g. user's target domains).", related_name='+', to='accounts.domain'),
        ),
    ]
