# Generated by Django 4.2.7 on 2026-02-22 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('assessments', '0004_studentassessmentattempt_test_domains'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentquestion',
            options={'ordering': ['domain', 'order', 'id']},
        ),
        migrations.RemoveField(
            model_name='assessmentquestion',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='studentassessmentattempt',
            name='assessment',
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='accounts.domain'),
        ),
        migrations.AlterField(
            model_name='studentassessmentattempt',
            name='test_domains',
            field=models.ManyToManyField(blank=True, help_text='Domains this test was taken for.', related_name='+', to='accounts.domain'),
        ),
        migrations.DeleteModel(
            name='SkillAssessment',
        ),
    ]
