# Generated by Django 4.2.7 on 2026-02-22 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('assessments', '0005_alter_assessmentquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentquestion',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='accounts.domain'),
        ),
    ]
